package com.gymquest.app.navigation

object NavRoutes {
    const val HOME = "home"
    const val CATALOG = "catalog"
    const val ROUTINES = "routines"
    const val SESSIONS = "sessions"
    const val ACTIVE_TRAINING_SESSION = "active_training_session/{sessionId}"
    const val SESSION_EXERCISE_CATALOG = "session_exercise_catalog/{sessionId}"
    const val ROUTINE_EXERCISE_CATALOG = "routine_exercise_catalog/{dayId}"
    const val CATALOG_DETAIL = "catalog_detail/{exerciseBaseId}"
    const val ADD_MUSCLE_GROUP = "add_muscle_group"
    const val ADD_EXERCISE = "add_exercise"
    const val ADD_VARIANT = "add_variant/{exerciseBaseId}"
    const val MARTIAL_ARTS = "martial_arts"
    const val MARTIAL_ART = "martial_art/{artId}"
    const val MARTIAL_STYLE = "martial_style/{styleId}"
    const val MARTIAL_CONTENT = "martial_content/{contentId}/{styleId}"
    const val MARTIAL_CREATE_CONTENT = "martial_create_content/{styleId}"
    const val MARTIAL_TECHNIQUE = "martial_technique/{techniqueId}/{styleId}"
    const val MARTIAL_CREATE_TECHNIQUE = "martial_create_technique/{styleId}"
    const val MARTIAL_STANCE = "martial_stance/{stanceId}/{styleId}"
    const val MARTIAL_CREATE_STANCE = "martial_create_stance/{styleId}"
    const val SETTINGS = "settings"
    const val BACKUP = "backup"
    fun martialArt(artId: Long) = "martial_art/$artId"
    fun catalogDetail(exerciseBaseId: Long) = "catalog_detail/$exerciseBaseId"
    fun addVariant(exerciseBaseId: Long) = "add_variant/$exerciseBaseId"
    fun activeTrainingSession(sessionId: Long) = "active_training_session/$sessionId"
    fun sessionExerciseCatalog(sessionId: Long) = "session_exercise_catalog/$sessionId"
    fun routineExerciseCatalog(dayId: Long) = "routine_exercise_catalog/$dayId"
    fun martialStyle(styleId: Long) = "martial_style/$styleId"
    fun martialContent(contentId: Long, styleId: Long) = "martial_content/$contentId/$styleId"
    fun martialCreateContent(styleId: Long) = "martial_create_content/$styleId"
    fun martialTechnique(techniqueId: Long, styleId: Long) = "martial_technique/$techniqueId/$styleId"
    fun martialCreateTechnique(styleId: Long) = "martial_create_technique/$styleId"
    fun martialStance(stanceId: Long, styleId: Long) = "martial_stance/$stanceId/$styleId"
    fun martialCreateStance(styleId: Long) = "martial_create_stance/$styleId"
}
